version: '3'

services:
  db:
    image: postgres
    container_name: postgres-fortbrasil
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  api:
    image: fortbrasil_api
    container_name: fortbrasil_api
    build: .
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
